java:
  image: ${IMAGE_NAME}
  applicationPort: 4400
  cpuRequests: 25m
  keyVaults:
    cmc:
      resourceGroup: cmc
      secrets:
        - AppInsightsInstrumentationKey
        - claim-store-s2s-secret
  environment:
    LOG_LEVEL: DEBUG
